config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from rest_framework.routers import DefaultRouter

from finhack_bca.frontend import views
from finhack_bca.transaction.views import TransactionViewSet
from finhack_bca.transaction.views import CounterTopUpViewSet
from finhack_bca.transaction.views import CustomerTopUpViewSet
from finhack_bca.transaction.views import confirm_transaction
from finhack_bca.store.views import StoreViewSet
from finhack_bca.utils.views import CustomerAutocomplete, api_root


# API
router = DefaultRouter()
router.register(r'api/transactions', TransactionViewSet, base_name='transaction')
router.register(r'api/countertopups', CounterTopUpViewSet, base_name='counter_top_up')
router.register(r'api/customertopups', CustomerTopUpViewSet, base_name='customer_top_up')
router.register(r'api/stores', StoreViewSet, base_name='store')

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),
    url(r'^daftar-toko/$', views.StoreListView.as_view(), name="list_toko"),
    url(r'^daftar-counter/$', views.counter_list_view, name="list_counter"),
    url(r'^konfirmasi/$', views.TransactionConfirmationView.as_view(), name="transaction_confirmation"),
    url(r'^developer/$', TemplateView.as_view(template_name='pages/developer.html'), name='developer'),
    url(r'^konfirmasi/kode/$', views.GetLatestCodeView.as_view(), name='get_transaction_code'),
    url(r'^topup/$', views.CreateCustomerTopUpView.as_view(), name='customer_top_up'),

    # Django Admin, use {% url 'admin:index' %}
    url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("finhack_bca.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^api/$', api_root),
    url(r'^api-auth/', include('rest_auth.urls')),
    url(r'^api/docs/', include('rest_framework_swagger.urls')),
    url(r'^api/registration/', include('rest_auth.registration.urls')),
    url(r'^api/confirmtransaction/', confirm_transaction, name='api_confirm_transaction'),
    url(r'^', include(router.urls)),

    # Autocompletes
    url(r'^customer-autocomplete/$', CustomerAutocomplete.as_view(), name='customer_autocomplete'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

finhack_bca/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

finhack_bca/store/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Store(models.Model):
    name = models.CharField(max_length=100)
    balance = models.IntegerField(default=0)
    domain = models.URLField()
    short_description = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Toko'
        verbose_name_plural = 'Toko'
        permissions = (
            ('view_store', 'Can view store'),
        )

finhack_bca/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from guardian.mixins import GuardianUserMixin

from finhack_bca.store.models import Store


TYPE = (
    ('counter', 'Counter'),
    ('customer', 'Customer'),
    ('staff', 'Staff'),
    ('store', 'Store')
)


@python_2_unicode_compatible
class User(AbstractUser, GuardianUserMixin):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    type = models.CharField(choices=TYPE, blank=True, null=True, max_length=20)

    # this meant for counter only
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)

    balance = models.IntegerField(default=0)

    # for store only
    stores = models.ManyToManyField(Store, blank=True)

    # BCA's mandatory fields, email is used as primary id bca
    date_of_birth = models.DateField(blank=True, null=True)
    mobile_number = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

finhack_bca/utils/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Location(models.Model):
    name = models.CharField(max_length=100)
    latitude = models.FloatField()
    longitude = models.FloatField()

finhack_bca/frontend/forms.py
from django import forms
from dal import autocomplete

from finhack_bca.transaction.models import Transaction, CustomerTopUp
from finhack_bca.users.models import User


class TransactionConfirmationForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(TransactionConfirmationForm, self).__init__(*args, **kwargs)
        self.fields['store'].disabled = True
        self.fields['remarks'].disabled = True
        self.fields['amount'].disabled = True

    class Meta:
        model = Transaction
        fields = ['store', 'remarks', 'amount']


class CustomerTopUpForm(forms.ModelForm):

    class Meta:
        model = CustomerTopUp
        fields = ['customer', 'amount']
        widgets = {
            'customer': autocomplete.ModelSelect2(url='customer_autocomplete')
        }

finhack_bca/users/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class SignupForm(forms.Form):
    name = forms.CharField(max_length=30, label=_('Name'))
    mobile_number = forms.CharField(max_length=30)

    # TODO clean mobile_number

    def signup(self, request, user):
        user.name = self.cleaned_data['name']
        user.mobile_number = self.cleaned_data['mobile_number']
        user.save()

finhack_bca/frontend/views.py
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.views.generic import ListView, CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render

from finhack_bca.store.models import Store
from finhack_bca.utils.models import Location
from finhack_bca.users.models import User
from finhack_bca.transaction.models import Transaction, CustomerTopUp
from finhack_bca.frontend.forms import TransactionConfirmationForm, CustomerTopUpForm


class StoreListView(ListView):
    model = Store
    template_name = 'pages/store_list.html'


def counter_list_view(request):
    context = {
        'counters': User.objects.filter(type='counter'),
        'locations': Location.objects.all()
    }
    template = 'pages/counter_list.html'
    return render(request, template, context)


class TransactionConfirmationView(LoginRequiredMixin, CreateView):
    template_name = 'pages/confirmation.html'
    model = Transaction
    form_class = TransactionConfirmationForm

    def get_success_url(self):
        return reverse("get_transaction_code")

    # TODO change status to false when implementing BCA's APIs
    def form_valid(self, form):
        user = self.request.user
        form.instance.customer = user
        form.instance.date = timezone.now()
        form.instance.status = True
        return super(TransactionConfirmationView, self).form_valid(form)

    # get initial data from URL query parameters
    def get_initial(self):
        if self.request.GET:
            store_id = int(self.request.GET.get('store'))
            self.request.session['store'] = Store.objects.get(id=store_id).pk
            self.request.session['remarks'] = self.request.GET.get('remarks')
            self.request.session['amount'] = self.request.GET.get('amount')
        return {
            'store': self.request.session['store'],
            'remarks': self.request.session['remarks'],
            'amount': self.request.session['amount'],
        }


class GetLatestCodeView(LoginRequiredMixin, TemplateView):
    template_name = 'pages/showcode.html'

    def get_context_data(self, **kwargs):
        context = {
            'latest_transaction': self.request.user.transactions.all().order_by('-id')[0]
        }
        return context


# TODO make forbidden for user that is not a counter
class CreateCustomerTopUpView(LoginRequiredMixin, CreateView):
    template_name = 'pages/customer_top_up.html'
    model = CustomerTopUp
    form_class = CustomerTopUpForm

    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    # TODO change status to false when implementing BCA's APIs
    def form_valid(self, form):
        counter = self.request.user
        form.instance.counter = counter
        form.instance.date = timezone.now()
        form.instance.status = True
        return super(CreateCustomerTopUpView, self).form_valid(form)

finhack_bca/store/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticated

from finhack_bca.store.serializers import StoreSerializer
from finhack_bca.store.models import Store


class StoreViewSet(viewsets.ReadOnlyModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = StoreSerializer
    queryset = Store.objects.all()

finhack_bca/transaction/views.py
from rest_framework import viewsets
from rest_framework.generics import GenericAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework import status
from rest_framework.decorators import api_view

from dry_rest_permissions.generics import DRYPermissions

from finhack_bca.transaction.models import Transaction, CounterTopUp, CustomerTopUp
from finhack_bca.transaction.serializers import TransactionSerializer
from finhack_bca.transaction.serializers import CounterTopUpSerializer
from finhack_bca.transaction.serializers import CustomerTopUpSerializer
from finhack_bca.transaction.serializers import ConfirmTransactionSerializer


class TransactionViewSet(viewsets.ReadOnlyModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = TransactionSerializer

    def get_queryset(self):
        user_type = self.request.user.type
        if user_type == 'customer' or user_type == 'counter':
            queryset = Transaction.objects.filter(customer=self.request.user)
        elif user_type == 'store':
            # if a store's user has more than one store
            store_ids = self.request.user.stores.all().values_list('id', flat=True)
            stores_ids_list = list(store_ids)
            queryset = Transaction.objects.filter(store__id__in=stores_ids_list)
        else:
            queryset = Transaction.objects.all()
        return queryset


class CounterTopUpViewSet(viewsets.ReadOnlyModelViewSet):
    permission_classes = (IsAuthenticated,)
    serializer_class = CounterTopUpSerializer

    def get_queryset(self):
        user_type = self.request.user.type
        if user_type == 'counter':
            queryset = CounterTopUp.objects.filter(counter=self.request.user)
        else:
            queryset = None
        return queryset


class CustomerTopUpViewSet(viewsets.ModelViewSet):
    serializer_class = CustomerTopUpSerializer
    permission_classes = (DRYPermissions,)

    def get_queryset(self):
        user_type = self.request.user.type
        if user_type == 'counter':
            queryset = CustomerTopUp.objects.filter(counter=self.request.user)
        elif user_type == 'customer':
            queryset = CustomerTopUp.objects.filter(customer=self.request.user)
        else:
            queryset = None
        return queryset


@api_view(['POST'])
def confirm_transaction(request):
    serializer = ConfirmTransactionSerializer(data=request.data)
    if request.method == 'POST':
        if serializer.is_valid():
            transaction_code = request.data['transaction_code']
            transaction = Transaction.objects.get(transaction_code=transaction_code)
            if transaction.status:
                return Response(serializer.data, status=status.HTTP_200_OK)
            else:
                return Response(serializer.data, status=status.HTTP_406_NOT_ACCEPTABLE)
        return Response(serializer.errors, status=status.HTTP_406_NOT_ACCEPTABLE)

finhack_bca/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

finhack_bca/utils/views.py
from dal import autocomplete

from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse

from finhack_bca.users.models import User


class CustomerAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = User.objects.filter(type='customer')

        if self.q:
            qs = qs.filter(username__istartswith=self.q)

        return qs

@api_view(('GET',))
def api_root(request, format=None):
    return Response({
        'confirm transaction': reverse('api_confirm_transaction', request=request, format=format),
        'transactions': reverse('transaction-list', request=request, format=format),
        'counter top ups': reverse('counter_top_up-list', request=request, format=format),
        'customer top ups': reverse('customer_top_up-list', request=request, format=format),
        'stores': reverse('store-list', request=request, format=format),
        'registration': reverse('rest_register', request=request, format=None),
        'verify email': reverse('rest_verify_email', request=request, format=None),
        'password reset': reverse('rest_password_reset', request=request, format=None),
        'password reset confirm': reverse('rest_password_reset_confirm', request=request, format=None),
        'login': reverse('rest_login', request=request, format=None),
        'logout': reverse('rest_logout', request=request, format=None),
        'user': reverse('rest_user_details', request=request, format=None),
        'password change': reverse('rest_password_change', request=request, format=None),
    })

finhack_bca/templates/users/user_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
  {% load humanize %}
  <div class="container">

    <div class="row margintop">
      <div class="col-sm-12">

        <h2>{{ object.username }} - {{ object.type }}</h2>
        {% if object.name %}
          <p>{{ object.name }}</p>
        {% endif %}
      </div>
    </div>

    {% if object == request.user %}
      <!-- Action buttons -->
      <div class="row">

        <div class="col-sm-12">
          <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
          <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
          <a class="btn btn-primary" href="{% url 'customer_top_up' %}">Top Up Pelanggan</a>
        </div>

        {% if object.type == 'customer' or object.type == 'counter' %}
        <div class="col-sm-12 margintop">
          <h4>Riwayat Top Up</h4>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Tanggal</th>
                <th>Counter</th>
                <th>Jumlah</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% if object.top_ups.all %}
                {% for topup in object.top_ups.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ topup.date }}</td>
                    <td>{{ topup.counter }}</td>
                    <td>IDR {{ topup.amount|intcomma }}</td>
                    <td>{{ topup.status }}</td>
                  </tr>
                  {% if forloop.last %}
                  {% endif %}
                {% endfor %}
              {% endif %}
              {% if object.counter_top_ups.all %}
                {% for topup in object.counter_top_ups.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ topup.date }}</td>
                    <td>{{ topup.counter }}</td>
                    <td>IDR {{ topup.amount|intcomma }}</td>
                    <td>{{ topup.status }}</td>
                  </tr>
                  {% if forloop.last %}
                  {% endif %}
                {% endfor %}
              {% endif %}
            </tbody>
          </table>
        </div>
        {% endif %}

        {% if object.customer_top_ups.all %}
          <div class="col-sm-12 margintop">
            <h4>Riwayat Top Up Pelanggan</h4>
            <table class="table table-striped table-hover">
              <thead>
                <tr>
                  <th></th>
                  <th>Tanggal</th>
                  <th>Pengguna</th>
                  <th>Jumlah</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {% for topup in object.customer_top_ups.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ topup.date }}</td>
                    <td>{{ topup.customer }}</td>
                    <td>IDR {{ topup.amount|intcomma }}</td>
                    <td>{{ topup.status }}</td>
                  </tr>
                  {% if forloop.last %}
                  {% endif %}
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% endif %}

        <div class="col-sm-12 margintop">
          <h4>Riwayat Transaksi</h4>
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th></th>
                <th>Tanggal</th>
                <th>Kode transaksi</th>
                <th>Toko</th>
                <th>Jumlah</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {% if object.stores.all %}
                {% for store in object.stores.all %}
                  {% for transaction in store.transactions.all %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ transaction.date }}</td>
                    <td>{{ transaction.transaction_code }}</td>
                    <td>{{ transaction.store }}</td>
                    <td>IDR {{ transaction.amount|intcomma }}</td>
                    <td>{{ transaction.status }}</td>
                  </tr>
                    {% endfor %}
                  {% if forloop.last %}
                  {% endif %}
                {% endfor %}
              {% else %}
                  {% for transaction in object.transactions.all %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td>{{ transaction.date }}</td>
                      <td>{{ transaction.transaction_code }}</td>
                      <td>{{ transaction.store }}</td>
                      <td>IDR {{ transaction.amount|intcomma }}</td>
                      <td>{{ transaction.status }}</td>
                    </tr>
                  {% endfor %}
                  {% if forloop.last %}
                  {% endif %}
              {% endif %}
            </tbody>
          </table>
        </div>

      </div>
      <!-- End Action buttons -->
    {% endif %}


  </div>
{% endblock content %}

finhack_bca/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

finhack_bca/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

</div>

{% endblock content %}